name: wird_book_share
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: '>=2.18.1 <3.0.0'

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  shared_preferences: ^2.0.15
  provider: ^6.0.3
  just_audio: ^0.9.28
  audio_video_progress_bar: ^0.9.0 
  gestures: ^1.0.0  
  flutter_animation_progress_bar: ^2.2.1
  audio_service: ^0.18.7
  card_swiper: ^2.0.4
  linear_progress_bar: "^1.1.0"
  google_fonts: ^3.0.1
  loading_animation_widget: ^1.2.0+3
  fullscreen: ^1.0.3
  percent_indicator: ^4.2.2
  flutter_launcher_icons: ^0.11.0
  auto_size_text: ^3.0.0
  cron: ^0.5.1
  zoom_widget: ^2.0.0
 
flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/logo.jpg"
  icon_size: 15
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: true
    # image_path: "path/to/image.png"
    background_color: "#hexcode"
    theme_color: "#hexcode"
  windows:
    generate: true
    image_path: "assets/images/logo.jpg"
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: "assets/images/logo.jpg"
dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^2.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - lib/lang/en.json 
    - lib/lang/ar.json 
    - lib/quran/Arabic_Quran.json
    - lib/quran/English_Quran.json 
    - lib/quran/Surah_List.json
    - lib/quran/page_wise_audio_format.json 
    - assets/images/surah_banner.png
    - assets/images/bismillah_banner.png
    - assets/images/bismillah_banner.jpg
    - assets/images/App_icon.png
    - assets/images/page_banner.png
    - assets/images/logo.jpg
    - assets/images/page_number.png
     
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Poppins
      fonts:
        - asset: fonts/Poppins-Regular.ttf 
    - family: ShareIcon
      fonts:
        - asset: fonts/ShareIcon.ttf
    - family: Noor
      fonts:
        - asset: fonts/noor-regular.ttf
         
    - family: Almushaf
      fonts:
        - asset: fonts/almushaf.ttf
    - family: Mushaf Madinah
      fonts:
        # - asset: fonts/almushaf.ttf 
        # - asset: fonts/noor-regular.ttf
        - asset: fonts/UthmanicHafs_V20.ttf 
        # - asset: fonts/UthmanicHafs1B Ver13.ttf 
        # - asset: fonts/noorehuda.ttf 
    - family: Mushaf Uthmani
      fonts:
        - asset: fonts/noor-regular.ttf
          
    - family: Rustam
      fonts:
        - asset: fonts/rustam_quranR3HOQ.ttf
         
    - family: Droid Nask
      fonts:
        - asset: fonts/DroidNaskh-Regular.ttf
         
    - family: Sakkal Majalla Regular
      fonts:
        - asset: fonts/Sakkal Majalla Regular.ttf
    - family: Al Jazeera Arabic Bold
      fonts:
        - asset: fonts/Al-Jazeera-Arabic Bold.ttf
    - family: Al Jazeera Arabic Regular
      fonts:
        - asset: fonts/Al-Jazeera-Arabic Regular.ttf
          
        
         
         
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
